Controllers/GeneroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parcial1.Data;
using Parcial1.Models;
using Parcial1.Services;
using Parcial1.ViewModels;

namespace Parcial1.Controllers
{
    public class GeneroController : Controller
    {
        private readonly VideojuegoContext _context;
        private readonly IGeneroService _generoService;

        public GeneroController(VideojuegoContext context, IGeneroService generoService)
        {
            _context = context;
            _generoService = generoService;
        }

        // GET: Genero
        public async Task<IActionResult> Index(string filtro)
        {
            var videojuegos = _generoService.GetAll();
            if (!string.IsNullOrEmpty(filtro) && !string.IsNullOrWhiteSpace(filtro))
            {
                videojuegos = videojuegos.Where(v => v.Nombre.ToLower().Contains(filtro.ToLower())||
                v.Descripcion.ToLower().Contains(filtro.ToLower())
                ).ToList();
            }
            return View(videojuegos.ToList());
        }
        [Authorize(Roles = "Administrador,Operador,Visualizador")]
        // GET: Genero/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _generoService.GetById(id.Value);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Genero/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Genero/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,Descripcion")] GeneroViewModel genero)
        {
            if (ModelState.IsValid)
            {
                await _generoService.Create(new Genero{
                    Nombre=genero.Nombre,
                    Descripcion=genero.Descripcion,
                });
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        [Authorize(Roles = "Administrador,Operador")]
        // GET: Genero/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _generoService.GetById(id.Value);
            if (genero == null)
            {
                return NotFound();
            }
            return View(genero);
        }

        // POST: Genero/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,VideojuegoId")] GeneroViewModel genero)
        {
            if (id != genero.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _generoService.Update(new Genero{
                    Id=genero.Id,
                    Nombre=genero.Nombre,
                    Descripcion=genero.Descripcion,
                });
                return RedirectToAction(nameof(Index));
            }
            return View(genero);
        }

        [Authorize(Roles = "Administrador,Operador")]
        // GET: Genero/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var genero = await _generoService.GetById(id.Value);
            if (genero == null)
            {
                return NotFound();
            }

            return View(genero);
        }

        // POST: Genero/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _generoService.Delete(id); 
            return RedirectToAction(nameof(Index));
        }

        private bool GeneroExists(int id)
        {
          return (_context.Genero?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/PlataformaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parcial1.Data;
using Parcial1.Models;
using Parcial1.Services;
using Parcial1.Utils;
using Parcial1.ViewModels;

namespace Parcial1.Controllers
{
    public class PlataformaController : Controller
    {
        private readonly VideojuegoContext _context;
        private readonly IPlataformaService _plataformaService;

        public PlataformaController(VideojuegoContext context, IPlataformaService plataformaService)
        {
            _context = context;
            _plataformaService=plataformaService;
        }

        // GET: Plataforma
        public async Task<IActionResult> Index(string filtro)
        {
            var plataformas = _plataformaService.GettAll();
            if (!string.IsNullOrEmpty(filtro) && !string.IsNullOrWhiteSpace(filtro))
            {
                plataformas = plataformas.Where(v => v.Nombre.ToLower().Contains(filtro.ToLower())||
                 v.Empresa.ToLower().Contains(filtro.ToLower())).ToList();
            }
            return View(plataformas.ToList());
        }
        [Authorize(Roles = "Administrador,Operador,Visualizador")]
        // GET: Plataforma/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plataforma = await _plataformaService.GetById(id.Value);

            return View(plataforma);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Plataforma/Create
        
        public IActionResult Create()
        {

            return View();
        }

        // POST: Plataforma/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Empresa")] PlataformaViewModel plataforma)
        {
            if (ModelState.IsValid)
            {
                await _plataformaService.Create(new Plataforma{
                    Nombre=plataforma.Nombre,
                    Empresa=plataforma.Empresa,
                });
                return RedirectToAction(nameof(Index));
            }
            return View(plataforma);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Plataforma/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Plataforma == null)
            {
                return NotFound();
            }

            var plataforma = await _plataformaService.GetById(id.Value);
            if (plataforma == null)
            {
                return NotFound();
            }
            return View(plataforma);
        }

        // POST: Plataforma/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Empresa")] PlataformaViewModel plataforma)
        {
            if (id != plataforma.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _plataformaService.Update(new Plataforma{
                    Id=plataforma.Id,
                    Nombre=plataforma.Nombre,
                    Empresa=plataforma.Empresa,
                });
                return RedirectToAction(nameof(Index));
            }
            return View(plataforma);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Plataforma/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plataforma = await _plataformaService.GetById(id.Value);
            if (plataforma == null)
            {
                return NotFound();
            }

            return View(plataforma);
        }

        // POST: Plataforma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _plataformaService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool PlataformaExists(int id)
        {
          return (_context.Plataforma?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/RolesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Parcial1.Models;
using Parcial1.Views.Roles.ViewModels;

namespace Parcial1.Controllers;

[Authorize(Roles = "Administrador")]
public class RolesController : Controller
{
    private readonly ILogger<HomeController> _logger;
    //Inyectamos el role manager
    private readonly RoleManager<IdentityRole> _roleManager;

    //Añadimos el userManager
    public RolesController(
        ILogger<HomeController> logger,
        RoleManager<IdentityRole> roleManager)
    {
        _logger = logger;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {
        //Listar todos los roles.
        var roles = _roleManager.Roles.ToList();
        return View(roles);
    }

    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Create(RoleCreateViewModel model)
    {
        if(string.IsNullOrEmpty(model.RoleName))
        {
            return View();
        }
        var role = new IdentityRole(model.RoleName);
        _roleManager.CreateAsync(role);

        return RedirectToAction("Index");
    }
}

Controllers/UsersController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Parcial1.Models;
using Parcial1.Views.Users.ViewModels;

namespace Parcial1.Controllers;

[Authorize(Roles = "Administrador")]
public class UsersController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly RoleManager<IdentityRole> _roleManager;

    public UsersController(
        ILogger<HomeController> logger,
        UserManager<IdentityUser> userManager,
        RoleManager<IdentityRole> roleManager)
    {
        _logger = logger;
        _userManager = userManager;
        _roleManager = roleManager;
    }

    public IActionResult Index()
    {
        
        var users = _userManager.Users.ToList();
        return View(users);
    }

    public async Task<IActionResult> Edit(string id)
    {
        var user = await _userManager.FindByIdAsync(id);
        ViewData["Roles"] = _roleManager.Roles.Select(x=> x.Name).ToList();
        var userViewModel = new UserEditViewModel();
        userViewModel.UserName = user.UserName ?? string.Empty;
        userViewModel.Email=user.Email ?? string.Empty;
        userViewModel.Roles=new SelectList(_roleManager.Roles.Select(x=> x.Name).ToList());
        return View(userViewModel);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(UserEditViewModel model)
    {
        var user = await _userManager.FindByNameAsync(model.UserName);
        if(user != null)
        {
            await _userManager.AddToRoleAsync(user, model.Role);
        }
        return RedirectToAction("Index");
    }

    

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parcial1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Parcial1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color: #281e5d;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color: white">EVideojuego</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Videojuego" asp-action="Index" style="color: white">Videojuego</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Genero" asp-action="Index" style="color: white">Genero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Plataforma" asp-action="Index" style="color: white">Plataforma</a>
                        </li>
@if (User.Identity != null && User.IsInRole("Administrador")){
                          <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Roles" asp-action="Index" style="color: white">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Users" asp-action="Index" style="color: white">Usuarios</a>
                        </li>  
}
                    </ul>
                    <partial name="_LoginPartial" />                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Parcial1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>