Models/Videojuego.cs
using Parcial1.Utils;
namespace Parcial1.Models;

public class Videojuego{
    public int Id { get; set; }
    public string Nombre { get; set; }
    public string Desarrollador { get; set; }
    public ViedeojuegoType RestriccionEdad{get;set;}
    public int Precio { get; set; }
    public int GeneroId{get;set;}
    public Genero Genero{get;set;}

    public virtual List<Plataforma> Plataformas{get;set;}
    
}

ViewModels/VideojuegoViewModel.cs
using Parcial1.Models;
using Parcial1.Utils;
using System.ComponentModel.DataAnnotations;
namespace Parcial1.ViewModels;

public class ViedeojuegoViewMOdel
{
    public int Id { get; set; }
    [Required(ErrorMessage ="Tiene que completarse este campo")]
    public string Nombre { get; set; }
    [Required(ErrorMessage ="Tiene que completarse este campo")]
    public string Desarrollador { get; set; }
    [Required(ErrorMessage ="Tiene que completarse este campo")]
    [Display(Name ="Restriccion de Edad")]
    public ViedeojuegoType RestriccionEdad { get; set; }
    [Required(ErrorMessage ="Tiene que completarse este campo")]
    [Range(2000,25000,ErrorMessage ="El rango entre precios es de $2000 hasta $25000")]
    public int Precio { get; set; }
    [Required(ErrorMessage ="Tiene que completarse este campo")]
    public int GeneroId{get;set;}
    public virtual List<int> Plataformas{get;set;}
}

Controllers/VideojuegoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Parcial1.Data;
using Parcial1.Models;
using Parcial1.Utils;
using Parcial1.Services;
using Parcial1.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Parcial1.Controllers
{
    public class VideojuegoController : Controller
    {
        private readonly VideojuegoContext _context;
        private readonly IVideojuegoService _videojuegoService;

        public VideojuegoController(VideojuegoContext context, IVideojuegoService videojuegoService)
        {
            _context = context;
            _videojuegoService = videojuegoService;
        }

        // GET: Videojuego
        public IActionResult Index(string filtro)
        {
            var videojuegos = _videojuegoService.GetAll();
            if (!string.IsNullOrEmpty(filtro) && !string.IsNullOrWhiteSpace(filtro))
            {
                videojuegos = videojuegos.Where(v => v.Nombre.ToLower().Contains(filtro.ToLower()) ||
                v.Desarrollador.ToLower().Contains(filtro.ToLower()) ||
                v.Genero.Nombre.ToLower().Contains(filtro.ToLower()) ||
                v.RestriccionEdad.ToString().ToLower().Contains(filtro.ToLower()) ||
                v.Precio.ToString().ToLower().Contains(filtro.ToLower())
                ).ToList();
            }
            return View(videojuegos.ToList());
        }
        [Authorize(Roles = "Administrador,Operador,Visualizador")]
        // GET: Videojuego/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Videojuego == null)
            {
                return NotFound();
            }

            var videojuego = await _videojuegoService.GetById(id.Value);
            if (videojuego == null)
            {
                return NotFound();
            }
            return View(videojuego);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Videojuego/Create  
        public IActionResult Create()
        {

            ViewBag.ViedeojuegoType = Enum.GetValues(typeof(ViedeojuegoType)).Cast<ViedeojuegoType>().Select(e => new SelectListItem
            {
                Text = e.ToString(),
                Value = ((int)e).ToString()
            }).ToList();

            ViewBag.Generos = new SelectList(_context.Genero.Select(g => new
            {
                Id = g.Id,
                Nombre = g.Nombre,

            }), "Id", "Nombre");

            ViewBag.Plataformas = new SelectList(_context.Plataforma.Select(g => new
            {
                Id = g.Id,
                Nombre = g.Nombre,

            }), "Id", "Nombre");
            return View();
        }

        // POST: Videojuego/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ViedeojuegoViewMOdel videojuego)
        {
            if (ModelState.IsValid)
            {
                await _videojuegoService.Create(new Videojuego
                {
                    GeneroId = videojuego.GeneroId,
                    Nombre = videojuego.Nombre,
                    Desarrollador = videojuego.Desarrollador,
                    RestriccionEdad = videojuego.RestriccionEdad,
                    Precio = videojuego.Precio,

                    
                },videojuego.Plataformas);
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "Id", "Id", videojuego.GeneroId);
            return View(videojuego);
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Videojuego/Edit/5    
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var videojuego = await _videojuegoService.GetById(id.Value);
            if (videojuego == null)
            {
                return NotFound();
            }
            var videojuegos = new ViedeojuegoViewMOdel()
            {
                GeneroId = videojuego.GeneroId,
                Nombre = videojuego.Nombre,
                Desarrollador = videojuego.Desarrollador,
                RestriccionEdad = videojuego.RestriccionEdad,
                Precio = videojuego.Precio,
            };
            ViewBag.ViedeojuegoType = Enum.GetValues(typeof(ViedeojuegoType)).Cast<ViedeojuegoType>().Select(e => new SelectListItem
            {
                Text = e.ToString(),
                Value = ((int)e).ToString()
            }).ToList();

            ViewBag.Generos = new SelectList(_context.Genero.Select(g => new
            {
                Id = g.Id,
                Nombre = g.Nombre,

            }), "Id", "Nombre");
            ViewBag.Plataformas = new SelectList(_context.Plataforma.Select(g => new
            {
                Id = g.Id,
                Nombre = g.Nombre,

            }), "Id", "Nombre");
            return View(videojuegos);
        }

        // POST: Videojuego/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,ViedeojuegoViewMOdel videojuego)
        {
            if (id != videojuego.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _videojuegoService.Update(new Videojuego
                {
                    Id = videojuego.Id,
                    GeneroId = videojuego.GeneroId,
                    Nombre = videojuego.Nombre,
                    Desarrollador = videojuego.Desarrollador,
                    RestriccionEdad = videojuego.RestriccionEdad,
                    Precio = videojuego.Precio,

                },videojuego.Plataformas);
                return RedirectToAction(nameof(Index));
            }
            ViewData["GeneroId"] = new SelectList(_context.Set<Genero>(), "Id", "Id", videojuego.GeneroId);
            return View(videojuego);
        }
        [Authorize(Roles = "Administrador,Operador")]
         public async Task<IActionResult> BlackFriday(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var videojuego = await _videojuegoService.GetById(id.Value);
            if (videojuego == null)
            {
                return NotFound();
            }
            var viewModel = new VideojuegoBlackFridayViewModel{
                Id=videojuego.Id,
                Nombre=videojuego.Nombre,
                Precio=videojuego.Precio,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BlackFriday(VideojuegoBlackFridayViewModel model, List<int> id)
        {
            var videojuego = await _videojuegoService.GetById(model.Id);
            if (videojuego == null)
            {
                return NotFound();
            }
            var cuenta = videojuego.Precio - (model.Porcentaje * videojuego.Precio/100);           
            if(model.Porcentaje>0 && cuenta>0)
            {
            videojuego.Precio= cuenta;
            await _videojuegoService.BlackFriday(videojuego);
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Administrador,Operador")]
        // GET: Videojuego/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var videojuego = await _videojuegoService.GetById(id.Value);
            if (videojuego == null)
            {
                return NotFound();
            }

            return View(videojuego);
        }

        // POST: Videojuego/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Videojuego == null)
            {
                return Problem("Entity set 'VideojuegoContext.Videojuego'  is null.");
            }
            await _videojuegoService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool VideojuegoExists(int id)
        {
            return (_context.Videojuego?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Videojuego/BlackFriday.cshtml
@model Parcial1.ViewModels.VideojuegoBlackFridayViewModel;

@{
    ViewData["Title"] = "Precio";
}

<h1>Aplicar descuento Black Friday</h1>

<h4>Videojuego</h4>
<hr />
<p>@Model.Nombre</p>
<div>
    <p>Precio actual: @Model.Precio</p>
</div>
<div class="row">
    <div class="col-md-4">
        <form asp-action="BlackFriday" method="post">
            <div class="form-group">
                <label asp-for="Porcentaje" class="control-label"></label>
                <input asp-for="Porcentaje" class="form-control" />
                <span asp-validation-for="Porcentaje" class="text-danger"></span>
            </div>
             <div class="form-group">
                <input type="submit" value="Aplicar descuento" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

Views/Videojuego/Create.cshtml
@model Parcial1.ViewModels.ViedeojuegoViewMOdel;

@{
    ViewData["Title"] = "Create";
}

<h1>Crear juego</h1>
<hr>
<h4>Videojuego</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desarrollador" class="control-label"></label>
                <input asp-for="Desarrollador" class="form-control" />
                <span asp-validation-for="Desarrollador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RestriccionEdad" class="control-label"></label>
                <select asp-items="ViewBag.ViedeojuegoType" asp-for="RestriccionEdad" class="form-control"></select>
                <span asp-validation-for="RestriccionEdad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class ="form-control" asp-items="ViewBag.Generos"></select>
            </div>
            <div class="form-group">
                <label asp-for="Plataformas" class="control-label"></label>
                @* <select asp-items="ViewBag.Plataformas" asp-for="Plataformas" class="form-control"></select> *@
            <select class="" multiple asp-for="Plataformas" id="Plataformas" asp-items="ViewBag.Plataformas" placeholder="select members" class="form-control w-50 dropdown">
            </select>
                <span asp-validation-for="Plataformas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Videojuego/Delete.cshtml
@model Parcial1.Models.Videojuego
@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>Estas seguro de que queres borrar este videojuego de la lista?</h3>
<div>
    <hr>
    <h5>Videojuego:</h5>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desarrollador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desarrollador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RestriccionEdad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RestriccionEdad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-dark" /> |
        <a asp-action="Index" class="btn btn-secondary" >Volver a la lista</a>
    </form>
</div>

Views/Videojuego/Details.cshtml
@model Parcial1.Models.Videojuego

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles</h1>

<div>
    <hr>
    <h5>Videojuego:</h5>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Desarrollador)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Desarrollador)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RestriccionEdad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RestriccionEdad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero.Nombre)
        </dd>
    </dl>
</div>
<h3>Plataformas disponible</h3>
@foreach (var item in Model.Plataformas)
{
    <li>@item.Nombre</li>
}
<div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model?.Id">Editar</a> |
    <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
</div>

Views/Videojuego/Edit.cshtml
@model Parcial1.ViewModels.ViedeojuegoViewMOdel;

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>
<hr>
<h4>Videojuego</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Desarrollador" class="control-label"></label>
                <input asp-for="Desarrollador" class="form-control" />
                <span asp-validation-for="Desarrollador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RestriccionEdad" class="control-label"></label>
                <select asp-items="ViewBag.ViedeojuegoType" asp-for="RestriccionEdad" class="form-control"></select>
                <span asp-validation-for="RestriccionEdad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio" class="control-label"></label>
                <input asp-for="Precio" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GeneroId" class="control-label"></label>
                <select asp-for="GeneroId" class="form-control" asp-items="ViewBag.Generos"></select>
                <span asp-validation-for="GeneroId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plataformas" class="control-label"></label>
            <select class="" multiple asp-for="Plataformas" id="Plataformas" asp-items="ViewBag.Plataformas" placeholder="select members" class="form-control w-50 dropdown">
            </select>
                <span asp-validation-for="Plataformas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-warning" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Volver a la lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Videojuego/Index.cshtml
@model IEnumerable<Parcial1.Models.Videojuego>

@{
    ViewData["Title"] = "Index";
    var Videojuego= ViewBag.Genero;
}

<h1>Lista de videojuegos</h1>

<p>
    <a asp-action="Create" class="btn btn-light">Crear un videojuego</a>
</p>
<form action="@Url.Action("Index","Videojuego")">
    @* <input class="form-control" type="text" name="filtro"> *@
    <input class="form-control" type="text" aria-label="readonly input example" name="filtro" readonlydisabled>
    <hr>
    <button class="btn btn-warning" type="submit">Buscar Videojuego</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Desarrollador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RestriccionEdad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Desarrollador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RestriccionEdad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero.Nombre)
            </td>
             @if (User.Identity != null && User.IsInRole("Administrador") || User.IsInRole("Operador")|| User.IsInRole("Visualizador")){
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-warning" >Detalles</a>
            </td>                
             }
            @if (User.Identity != null && User.IsInRole("Administrador") || User.IsInRole("Operador")){
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a> |
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-warning">Borrar</a> |
                <a asp-action="BlackFriday" asp-route-id="@item.Id" class="btn btn-warning">Aplicar BlackFriday</a>
            </td>
            }
        </tr>
}
    </tbody>
</table>